package com.sandeshsudake.mesa.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;

@Document
@Data
public class event {

    @Id
    private String eventID; // This will be auto-generated by MongoDB if null on save

    private String eventName;
    private String eventDesc;
    private String TOE;
    private LocalDate DOE;
    private int eventFees; // <--- CORRECTED: Changed from String to int
    private String eventLoc;

    private byte[] eventIMG;
    private String contentType;
}